# Generated by Django 5.2.16 on 2026-07-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_bankaccount_payment"),
        (
            "purchasing",
            "0002_purchaseorder_warehouse_purchaseorderitem_product_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="purchasing.bill",
            ),
        ),
    ]
