# Generated by Django 5.2.16 on 2026-07-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_tenant_address_tenant_phone_auditlog"),
        ("finance", "0004_invoice_currency_invoice_exchange_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_number", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=150)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("acquisition_date", models.DateField()),
                (
                    "acquisition_cost",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "salvage_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "useful_life_months",
                    models.PositiveIntegerField(help_text="Umur manfaat dalam bulan."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FULLY_DEPRECIATED", "Fully Depreciated"),
                            ("DISPOSED", "Disposed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("disposal_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accumulated_depreciation_account",
                    models.ForeignKey(
                        help_text="Akun kontra-aset akumulasi penyusutan.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="finance.account",
                    ),
                ),
                (
                    "asset_account",
                    models.ForeignKey(
                        help_text="Akun aset tetap (mis. Peralatan Kantor).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="finance.account",
                    ),
                ),
                (
                    "depreciation_expense_account",
                    models.ForeignKey(
                        help_text="Akun beban penyusutan.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="finance.account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_number"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.DateField(help_text="Tanggal 1 dari bulan yang diposting."),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "fixed_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_entries",
                        to="assets.fixedasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-period"],
            },
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.UniqueConstraint(
                fields=("tenant", "asset_number"), name="unique_asset_number_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="depreciationentry",
            constraint=models.UniqueConstraint(
                fields=("fixed_asset", "period"), name="unique_depreciation_per_period"
            ),
        ),
    ]
