# Generated by Django 5.2.16 on 2026-07-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_tenant_address_tenant_phone_auditlog"),
        ("finance", "0002_bankaccount_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=150)),
                ("unit", models.CharField(default="pcs", max_length=20)),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "sell_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("track_inventory", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cogs_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Akun beban HPP (Cost of Goods Sold).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="finance.account",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Akun aset persediaan. Kalau kosong, mutasi stok tidak posting ke jurnal.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="finance.account",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("address", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positif untuk stok masuk, negatif untuk stok keluar.",
                        max_digits=14,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "Penerimaan"),
                            ("DELIVERY", "Pengiriman"),
                            ("ADJUSTMENT", "Penyesuaian"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=50)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="inventory.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("tenant", "sku"), name="unique_product_sku_per_tenant"
            ),
        ),
    ]
