# Generated by Django 5.2.16 on 2026-07-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchasing",
            "0002_purchaseorder_warehouse_purchaseorderitem_product_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="currency",
            field=models.CharField(
                choices=[
                    ("IDR", "IDR - Rupiah"),
                    ("USD", "USD - US Dollar"),
                    ("EUR", "EUR - Euro"),
                    ("SGD", "SGD - Singapore Dollar"),
                    ("JPY", "JPY - Japanese Yen"),
                    ("CNY", "CNY - Chinese Yuan"),
                    ("AUD", "AUD - Australian Dollar"),
                    ("GBP", "GBP - British Pound"),
                ],
                default="IDR",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="Kurs ke IDR pada tanggal transaksi. Biarkan 1 untuk bill dalam IDR.",
                max_digits=14,
            ),
        ),
    ]
